#pragma once

// Limits
#define MAX_NAME_LENGTH 20
#define MAX_BUFFER_SIZE 1420
#define MAX_VERSION_STRING_LENGTH 20
#define MAX_MESSAGE_LENGTH 550

// TCP / UDP
#define INTERVAL_TCP_MESSAGE_MS 120
#define INTERVAL_UDP_MESSAGE_MS 3
#define INTERVAL_KEEPALIVE_SEC 15
